"""
Temporal enricher — fills in `unusual_time` and may override `timestamp`.

NOTE: The timestamp is *already* generated by TransactionGenerator before
enrichment begins, so this enricher only decorates it (unusual_time flag).
The time anomaly override driven by fraud patterns is handled in FraudEnricher.
"""

from typing import Any, Dict

from .base import EnricherProtocol, GeneratorBag


class TemporalEnricher:
    """Adds `unusual_time` flag from the transaction timestamp hour."""

    def enrich(self, tx: Dict[str, Any], bag: GeneratorBag) -> None:
        hour = tx.get("timestamp", "")
        # timestamp is an ISO string at this point — extract hour
        try:
            hour_int = int(str(tx.get("timestamp", "T00"))[-8:-6].lstrip("T"))
        except (ValueError, TypeError):
            hour_int = 0
        # Re-derive from the actual datetime if available
        ts = bag.timestamp
        if ts is not None and hasattr(ts, "hour"):
            hour_int = ts.hour
        tx["unusual_time"] = hour_int < 6 or hour_int > 23
